# Generated by Django 4.0.1 on 2022-04-23 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hostel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hostel_Name', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(max_length=20)),
                ('First_name', models.CharField(max_length=20)),
                ('Last_name', models.CharField(max_length=20)),
                ('Regnum', models.CharField(max_length=20)),
                ('Gender', models.CharField(max_length=20)),
                ('Room_no', models.IntegerField(null=True)),
                ('Email', models.CharField(max_length=40)),
                ('Phone_no', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.hostel')),
            ],
        ),
    ]
