# Generated by Django 4.0.1 on 2022-04-26 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mess_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('day', models.CharField(max_length=30)),
                ('desc', models.TextField(null=True)),
                ('Price', models.IntegerField(null=True)),
                ('time', models.CharField(blank=True, choices=[('Lunch', 'lunch'), ('Dinner', 'dinner')], max_length=8)),
            ],
        ),
    ]
